# Generated by Django 5.0.3 on 2024-04-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('date_of_birth', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('father_number', models.CharField(max_length=50)),
                ('father_occupation', models.CharField(max_length=50)),
            ],
        ),
    ]
