# Generated by Django 5.0.3 on 2024-04-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_student_branch_student_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default='sample@gmail.com', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='sample', max_length=50),
        ),
    ]
