# Generated by Django 5.0.3 on 2024-06-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_staff_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_leave',
            name='disapprove',
            field=models.BooleanField(default=False),
        ),
    ]
