# Generated by Django 5.0.3 on 2024-06-04 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_student_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_date', models.DateField(auto_now_add=True)),
                ('message', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('disapprove', models.BooleanField(default=False)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
    ]
