# Generated by Django 5.0.3 on 2024-06-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_result_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_feedback',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student_feedback',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
