# Generated by Django 5.0.3 on 2024-07-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_library'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'verbose_name_plural': 'Library'},
        ),
        migrations.AlterField(
            model_name='library',
            name='book_name',
            field=models.CharField(max_length=50),
        ),
    ]
